# gitlab-ci

variables:
  IMAGE: registry.gitlab.com/nalbam/sample-web:latest

stages:
  - build
  - release

build:
  stage: build
  image: nalbam/builder:alpine
  only:
    - master
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -t $IMAGE .

release:
  stage: release
  image: nalbam/builder:alpine
  only:
    - master
  script:
    - docker push $IMAGE

after_script:
  - ls -alh target
