replicaCount: 1
image:
  repository: docker-registry.127.0.0.1.nip.io:30500/sample-web
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  externalPort: 80
  internalPort: 80
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 128Mi
ingress:
  enabled: true
  basedomain: 127.0.0.1.nip.io
hpa:
  enabled: true
  min: 1
  max: 5
  cpu: 50
profile: default
configmap:
  enabled: false
secret:
  enabled: false
