replicaCount: 2
image:
  repository: acme
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  externalPort: 80
  internalPort: 80
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
ingress:
  enabled: true
  basedomain: apps.opspresso.com
hpa:
  enabled: true
  min: 2
  max: 30
  cpu: 50
configmap:
  enabled: false
secret:
  enabled: false
